apiVersion: v1
kind: Pod
metadata:
  name: kubia-liveness
  labels:
    app: kubia-liveness
    bug: "true"
spec:
  containers:
    - image: paxprz/unhealthy-kubia
      name: kubia
      livenessProbe:
        httpGet:
          path: /
          port: 8080
        initialDelaySeconds: 5
