apiVersion: v1
kind: Pod
metadata:
  name: kubia-pod
  labels:
    app: kubia
    name: kubia-pod
  annotations:
    created_by: |
      {"user": "PaxPrz", "fullname": "Prakash Prajapati"}
spec:
  containers:
  - name: kubia
    image: paxprz/kubia
    resources:
      limits:
        memory: "128Mi"
        cpu: "200m"
    ports:
      - containerPort: 8080
        protocol: TCP
